# consente di configurare e documentare tutte le dipendenze di servizio dell'applicazione,come altri servizi, cache, database, code...
# successivamente con il comando "docker-compose up -d" esegue il lavoro dei comandi docker-compose build e docker-compose run cioè
# Costruisce le immagini se non si trovano localmente e avvia i contenitori. Se le immagini sono già create, eseguirà il fork direttamente del contenitore.

services:
  app:
    image: php:8.1-apache
    container_name: Myshop-php
    volumes:
     - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - mariadb
    environment:
      # Variabili per MySQL
      - MYSQL_HOST= mysql
      - MYSQL_ROOT_PASSWORD= Sandonaci94
      - MYSQL_DATABASE= myshop
      

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Sandonaci94
      MYSQL_DATABASE: myshop
    ports:
      - "3306:3306"
        

  mariadb:
    image: mariadb
    container_name: mariadb-db
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: Sandonaci94
       MYSQL_DATABASE: myshop
    ports:
      - "3307:3306"

volumes:
  mysql_data:
  mariadb_data:

networks:
  myshop:
    driver: bridge

# networks:
#  myshop
  
# services: 
#  MariaDB  
# dbeaver (app da scaricare per collegarsi sul container)